# Generated by Django 5.2.8 on 2025-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campus', models.CharField(choices=[('north', 'North Campus'), ('south', 'South Campus'), ('off', 'Off Campus')], max_length=10)),
                ('short_intro', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_range', models.CharField(blank=True, max_length=50)),
                ('menu_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
